[versions]
agp = "8.3.1"
coreKtx = "1.5.0"
coreKtxVersion = "1.4.0"
espressoCoreVersion = "3.4.0"
junit = "4.13.2"
junitKtx = "1.1.3"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
lombok = "1.18.30"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
navigationFragment = "2.7.7"
navigationUi = "2.7.7"
roomCommon = "2.6.1"
roomRuntime = "2.6.1"
roomCompiler = "2.6.1"
runner = "1.5.2"
runnerVersion = "1.4.0"

[libraries]
core = { module = "androidx.test:core", version.ref = "coreKtx" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtx" }
core-ktx-v140 = { module = "androidx.test:core-ktx", version.ref = "coreKtxVersion" }
espresso-core-v340 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitVersion" }
junit-ktx-v113 = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
projectlombok-lombok = { module = "org.projectlombok:lombok", version = "1.18.30" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
runner-v140 = { module = "androidx.test:runner", version.ref = "runnerVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

